-- =============================================================================
-- Curso: Bases de Datos Relacionales
-- Docente: Juan Dario Rodas - jdrodas@hotmail.com
-- Unidad 4: Lógica almacenada
-- Archivo: 00_schema.sql
-- Propósito: Modelo relacional diseñado para soportar escenarios que requieren
--            procedimientos almacenados, funciones definidas por el usuario
--            y triggers.
-- Motor: PostgreSQL 16+
-- =============================================================================

-- -----------------------------------------------------------------------------
-- INSTRUCCIONES PARA COMPLETAR ESTE ARCHIVO
-- -----------------------------------------------------------------------------
-- 1. Define las tablas que serán objeto de lógica almacenada en esta unidad.
-- 2. Comenta qué objeto actuará sobre cada tabla
--    (ej: -- Esta tabla es auditada por el trigger trg_auditoria_pedidos).
-- 3. El diseño debe evidenciar autonomía y madurez plena en las decisiones.
-- 4. Incluye tablas de auditoría o bitácora si los triggers las requieren.
-- -----------------------------------------------------------------------------

-- Ejemplo de tabla principal:
-- CREATE TABLE pedido (
--     id            SERIAL          PRIMARY KEY,
--     cliente_id    INTEGER         NOT NULL REFERENCES cliente(id),
--     total         NUMERIC(12,2)   NOT NULL DEFAULT 0,
--     estado        VARCHAR(20)     NOT NULL DEFAULT 'pendiente',
--     creado_en     TIMESTAMP       NOT NULL DEFAULT NOW()
-- );

-- Ejemplo de tabla de auditoría:
-- CREATE TABLE auditoria_pedido (
--     id               SERIAL      PRIMARY KEY,
--     pedido_id        INTEGER     NOT NULL,
--     accion           VARCHAR(10) NOT NULL, -- INSERT, UPDATE, DELETE
--     estado_anterior  VARCHAR(20),
--     estado_nuevo     VARCHAR(20),
--     modificado_en    TIMESTAMP   NOT NULL DEFAULT NOW()
-- );
