-- =============================================================================
-- Curso: Bases de Datos Relacionales
-- Docente: Juan Dario Rodas - jdrodas@hotmail.com
-- Unidad 4: Lógica almacenada
-- Archivo: 04_triggers.sql
-- Propósito: Triggers que automatizan respuestas a eventos de datos,
--            garantizando integridad y consistencia del modelo.
-- Motor: PostgreSQL 16+
-- Prerequisito: ejecutar 00_schema.sql y 01_seed.sql antes de este archivo.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- INSTRUCCIONES PARA COMPLETAR ESTE ARCHIVO
-- -----------------------------------------------------------------------------
-- Implementa triggers para al menos dos tipos de eventos distintos
-- (INSERT, UPDATE o DELETE). Para cada trigger:
--   1. Define primero la función trigger (RETURNS TRIGGER).
--   2. Crea el trigger que la invoca sobre la tabla correspondiente.
--   3. Incluye comentario explicando la regla de integridad que implementa.
--   4. Incluye al final un ejemplo de operación que active el trigger.
-- -----------------------------------------------------------------------------

-- Ejemplo de trigger AFTER INSERT (reemplazar con lógica real):
-- CREATE OR REPLACE FUNCTION fn_auditoria_insert()
-- RETURNS TRIGGER LANGUAGE plpgsql AS $$
-- BEGIN
--     INSERT INTO auditoria_pedido (pedido_id, accion, estado_nuevo, modificado_en)
--     VALUES (NEW.id, 'INSERT', NEW.estado, NOW());
--     RETURN NEW;
-- END;
-- $$;
--
-- CREATE TRIGGER trg_auditoria_insert
-- AFTER INSERT ON pedido
-- FOR EACH ROW EXECUTE FUNCTION fn_auditoria_insert();


-- Ejemplo de trigger AFTER UPDATE (reemplazar con lógica real):
-- CREATE OR REPLACE FUNCTION fn_auditoria_update()
-- RETURNS TRIGGER LANGUAGE plpgsql AS $$
-- BEGIN
--     INSERT INTO auditoria_pedido (pedido_id, accion, estado_anterior, estado_nuevo, modificado_en)
--     VALUES (NEW.id, 'UPDATE', OLD.estado, NEW.estado, NOW());
--     RETURN NEW;
-- END;
-- $$;
--
-- CREATE TRIGGER trg_auditoria_update
-- AFTER UPDATE ON pedido
-- FOR EACH ROW EXECUTE FUNCTION fn_auditoria_update();
