-- =============================================================================
-- Curso: Bases de Datos Relacionales
-- Docente: Juan Dario Rodas - jdrodas@hotmail.com
-- Unidad 4: Lógica almacenada
-- Archivo: 02_stored_procedures.sql
-- Propósito: Procedimientos almacenados que encapsulan lógica de negocio
--            reutilizable del dominio de la cohorte.
-- Motor: PostgreSQL 16+
-- Prerequisito: ejecutar 00_schema.sql y 01_seed.sql antes de este archivo.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- INSTRUCCIONES PARA COMPLETAR ESTE ARCHIVO
-- -----------------------------------------------------------------------------
-- Cada procedimiento debe incluir:
--   - Comentario con el propósito y la regla de negocio que implementa.
--   - Parámetros de entrada (IN) y salida (OUT) claramente definidos.
--   - Manejo de errores con EXCEPTION y RAISE.
--   - Ejemplo de llamada al procedimiento al final del bloque.
-- -----------------------------------------------------------------------------

-- Ejemplo de estructura esperada (reemplazar con lógica real):
-- CREATE OR REPLACE PROCEDURE procesar_pedido(
--     IN  p_pedido_id  INTEGER,
--     OUT p_resultado  VARCHAR
-- )
-- LANGUAGE plpgsql
-- AS $$
-- BEGIN
--     IF NOT EXISTS (SELECT 1 FROM pedido WHERE id = p_pedido_id) THEN
--         RAISE EXCEPTION 'El pedido % no existe.', p_pedido_id;
--     END IF;
--
--     UPDATE pedido SET estado = 'procesado' WHERE id = p_pedido_id;
--     p_resultado := 'Pedido procesado exitosamente.';
--
-- EXCEPTION
--     WHEN OTHERS THEN
--         p_resultado := 'Error: ' || SQLERRM;
-- END;
-- $$;

-- Ejemplo de llamada:
-- CALL procesar_pedido(1, NULL);
