-- =============================================================================
-- Curso: Bases de Datos Relacionales
-- Docente: Juan Dario Rodas - jdrodas@hotmail.com
-- Unidad 3: SQL avanzado
-- Archivo: 01_seed.sql
-- Propósito: Inserción de datos de prueba para las nuevas entidades definidas
--            en 00_schema.sql de esta unidad.
-- Motor: PostgreSQL 16+
-- Prerequisito: ejecutar 00_schema.sql de esta unidad antes de este archivo.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- INSTRUCCIONES PARA COMPLETAR ESTE ARCHIVO
-- -----------------------------------------------------------------------------
-- 1. Inserta datos suficientes para que los JOINs entre múltiples tablas
--    retornen resultados significativos (mínimo 15 registros por tabla principal).
-- 2. Incluye registros que permitan ejercitar subconsultas correlacionadas
--    (ej. registros con y sin coincidencias en otras tablas).
-- 3. Asegura variedad en valores numéricos y temporales para que las funciones
--    de ventana produzcan rankings y acumulados visibles.
-- -----------------------------------------------------------------------------

-- Ejemplo de estructura esperada (reemplazar con datos reales):
-- INSERT INTO entidad_relacionada (tabla_a_id, tabla_b_id, cantidad, registrado_en) VALUES
--     (1, 2, 150.00, '2024-01-10 10:00:00'),
--     (1, 3, 200.50, '2024-01-15 11:30:00'),
--     (2, 1,  75.25, '2024-02-01 09:00:00');
