-- =============================================================================
-- Curso: Bases de Datos Relacionales
-- Docente: Juan Dario Rodas - jdrodas@hotmail.com
-- Unidad 3: SQL avanzado
-- Archivo: 04_ctes.sql
-- Propósito: Ejemplos de referencia de CTEs simples y recursivas aplicadas
--            al dominio de la cohorte.
-- Motor: PostgreSQL 16+
-- Prerequisito: ejecutar 00_schema.sql y 01_seed.sql antes de este archivo.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- SECCIÓN 1: CTE simple
-- -----------------------------------------------------------------------------
-- Pregunta de negocio: (describir aquí qué información se busca obtener)
-- WITH resumen AS (
--     SELECT  tabla_a_id,
--             COUNT(*)      AS total,
--             SUM(cantidad) AS suma_total
--     FROM    tabla_b
--     GROUP BY tabla_a_id
-- )
-- SELECT  a.nombre,
--         r.total,
--         r.suma_total
-- FROM    resumen r
--         INNER JOIN tabla_a a ON a.id = r.tabla_a_id
-- ORDER BY r.suma_total DESC;


-- -----------------------------------------------------------------------------
-- SECCIÓN 2: CTE recursiva
-- -----------------------------------------------------------------------------
-- Pregunta de negocio: (describir aquí qué información se busca obtener)
-- WITH RECURSIVE jerarquia AS (
--     -- Caso base
--     SELECT id, nombre, padre_id, 0 AS nivel
--     FROM   tabla_jerarquica
--     WHERE  padre_id IS NULL
--
--     UNION ALL
--
--     -- Caso recursivo
--     SELECT  t.id, t.nombre, t.padre_id, j.nivel + 1
--     FROM    tabla_jerarquica t
--             INNER JOIN jerarquia j ON t.padre_id = j.id
-- )
-- SELECT * FROM jerarquia ORDER BY nivel, nombre;
