-- =============================================================================
-- Curso: Bases de Datos Relacionales
-- Docente: Juan Dario Rodas - jdrodas@hotmail.com
-- Unidad 2: Fundamentos de SQL y operaciones básicas
-- Archivo: 00_schema.sql
-- Propósito: Extensión del modelo relacional de la Unidad 1 incorporando
--            nuevas entidades y relaciones que soporten operaciones de
--            consulta y agrupamiento.
-- Motor: PostgreSQL 16+
-- Prerequisito: ejecutar todos los scripts de unit-01 antes de este archivo.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- INSTRUCCIONES PARA COMPLETAR ESTE ARCHIVO
-- -----------------------------------------------------------------------------
-- 1. Define únicamente las tablas NUEVAS que extienden el modelo de la Unidad 1.
--    No redefinas tablas ya existentes.
-- 2. Las nuevas tablas deben estar correctamente normalizadas (mínimo 3FN).
-- 3. Evidencia mejoras en nomenclatura respecto a la entrega anterior.
-- 4. Incluye comentario por tabla explicando su rol en la extensión del modelo.
-- -----------------------------------------------------------------------------

-- Ejemplo de estructura esperada (reemplazar con el modelo real):
-- CREATE TABLE nueva_entidad (
--     id               SERIAL          PRIMARY KEY,
--     entidad_id       INTEGER         NOT NULL REFERENCES nombre_entidad(id),
--     valor            VARCHAR(100)    NOT NULL,
--     registrado_en    TIMESTAMP       NOT NULL DEFAULT NOW()
-- );
