-- =============================================================================
-- Curso: Bases de Datos Relacionales
-- Docente: Juan Dario Rodas - jdrodas@hotmail.com
-- Unidad 2: Fundamentos de SQL y operaciones básicas
-- Archivo: 01_seed.sql
-- Propósito: Inserción de datos de prueba para las nuevas entidades definidas
--            en 00_schema.sql de esta unidad.
-- Motor: PostgreSQL 16+
-- Prerequisito: ejecutar 00_schema.sql de esta unidad antes de este archivo.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- INSTRUCCIONES PARA COMPLETAR ESTE ARCHIVO
-- -----------------------------------------------------------------------------
-- 1. Inserta datos representativos del dominio para las tablas nuevas.
-- 2. Incluye valores que permitan ejercitar GROUP BY y funciones agregadas.
-- 3. Usa tipos TIMESTAMP con valores variados para practicar funciones de fecha.
-- 4. Asegura volumen suficiente de datos para que los agrupamientos sean
--    significativos (mínimo 10 registros por tabla principal).
-- -----------------------------------------------------------------------------

-- Ejemplo de estructura esperada (reemplazar con datos reales):
-- INSERT INTO nueva_entidad (entidad_id, valor, registrado_en) VALUES
--     (1, 'Valor A', '2024-01-15 08:30:00'),
--     (1, 'Valor B', '2024-02-20 14:00:00'),
--     (2, 'Valor C', '2024-03-10 09:15:00');
