-- =============================================================================
-- Curso: Bases de Datos Relacionales
-- Docente: Juan Dario Rodas - jdrodas@hotmail.com
-- Unidad 5: Transacciones, concurrencia y pruebas
-- Archivo: 00_schema.sql
-- Propósito: Modelo relacional orientado a un escenario donde la integridad
--            transaccional y el control de concurrencia son requisitos críticos.
-- Motor: PostgreSQL 16+
-- =============================================================================

-- -----------------------------------------------------------------------------
-- INSTRUCCIONES PARA COMPLETAR ESTE ARCHIVO
-- -----------------------------------------------------------------------------
-- 1. Define las tablas del escenario transaccional del dominio de la cohorte.
-- 2. Identifica y comenta en qué tablas ocurrirán operaciones concurrentes.
-- 3. El diseño debe reflejar madurez y autonomía plena: nomenclatura,
--    normalización y restricciones impecables.
-- 4. Considera columnas de control como versión o timestamps de modificación
--    si el escenario de concurrencia lo justifica.
-- -----------------------------------------------------------------------------

-- Ejemplo de estructura esperada (reemplazar con el modelo real):
-- CREATE TABLE cuenta (
--     id              SERIAL          PRIMARY KEY,
--     titular         VARCHAR(100)    NOT NULL,
--     saldo           NUMERIC(14,2)   NOT NULL DEFAULT 0 CHECK (saldo >= 0),
--     version         INTEGER         NOT NULL DEFAULT 0,
--     actualizado_en  TIMESTAMP       NOT NULL DEFAULT NOW()
-- );
