-- =============================================================================
-- Curso: Bases de Datos Relacionales
-- Docente: Juan Dario Rodas - jdrodas@hotmail.com
-- Unidad 5: Transacciones, concurrencia y pruebas
-- Archivo: 01_seed.sql
-- Propósito: Inserción de datos de prueba base para ejercitar las transacciones
--            y los casos de prueba unitaria de la unidad.
-- Motor: PostgreSQL 16+
-- Prerequisito: ejecutar 00_schema.sql de esta unidad antes de este archivo.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- INSTRUCCIONES PARA COMPLETAR ESTE ARCHIVO
-- -----------------------------------------------------------------------------
-- 1. Inserta datos que representen estados iniciales válidos del escenario
--    transaccional (ej. cuentas con saldo, inventarios con stock, etc.).
-- 2. Incluye registros que permitan simular tanto escenarios de éxito como
--    de fallo (ej. saldo insuficiente, stock agotado).
-- 3. Los datos deben ser suficientes para que los casos de prueba sean
--    significativos y reproducibles.
-- -----------------------------------------------------------------------------

-- Ejemplo de estructura esperada (reemplazar con datos reales):
-- INSERT INTO cuenta (titular, saldo) VALUES
--     ('Cliente A', 1000.00),
--     ('Cliente B',  250.00),
--     ('Cliente C',    0.00);
