-- =============================================================================
-- Curso: Bases de Datos Relacionales
-- Docente: Juan Dario Rodas - jdrodas@hotmail.com
-- Unidad 1: Fundamentos y diseño de bases de datos relacionales
-- Archivo: 00_schema.sql
-- Propósito: Creación de tablas, tipos de datos y restricciones de integridad
--            que conforman el modelo relacional base del dominio de la cohorte.
-- Motor: PostgreSQL 16+
-- =============================================================================

-- -----------------------------------------------------------------------------
-- INSTRUCCIONES PARA COMPLETAR ESTE ARCHIVO
-- -----------------------------------------------------------------------------
-- 1. Define aquí todas las tablas del modelo relacional diseñado en la Unidad 1.
-- 2. Cada tabla debe incluir:
--      - Clave primaria (PRIMARY KEY)
--      - Claves foráneas (FOREIGN KEY) donde aplique
--      - Restricciones NOT NULL en atributos obligatorios
--      - Tipos de datos apropiados (VARCHAR, TIMESTAMP, INTEGER, etc.)
-- 3. Las tablas deben cumplir al menos con la Tercera Forma Normal (3FN).
-- 4. Incluye un comentario breve sobre cada tabla explicando su propósito.
-- -----------------------------------------------------------------------------

-- Ejemplo de estructura esperada (reemplazar con el modelo real):
-- CREATE TABLE nombre_entidad (
--     id               SERIAL          PRIMARY KEY,
--     nombre           VARCHAR(100)    NOT NULL,
--     descripcion      VARCHAR(255),
--     creado_en        TIMESTAMP       NOT NULL DEFAULT NOW()
-- );
